# Github action to build newsletter.
#

name: newsletter

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install python libraries
        run: pip3 install --user -r requirements.txt

      - name: newsletter
        run: python newsletter/newsletter.py ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Monthly newsletter
          committer: Fortran <53436240+fortran-lang@users.noreply.github.com>
          author: Fortran <53436240+fortran-lang@users.noreply.github.com>
          branch: newsletter
          delete-branch: true
          title: 'Monthly newsletter'
          body: |
            Monthly newsletter
          reviewers: awvwgk, certik, milancurcic, gnikit

